spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_db
    username: root
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false

  flyway:
    user: root
    password: test
    url: jdbc:mysql://localhost:3306/school_db

settings:
  max-students-per-course: 50
  max-courses-per-student: 5